### ISSUE TITLE
[Discussion] Build Process

### ISSUE THREAD

**Issue by BoxcarFields** [cilix-lab/ubuntu-wrt#1]
Hi @cilix-lab 

Could you share your build notes around how you built Ubuntu for your router? I would like to give it a shot for my WRT1900ACv1.

Sid

**Comment by cilix-lab** [comment]
Sure thing. I've tried to make it as easy as possible. Here it goes...
1. Get the Ubuntu Linux Kernel (https://wiki.ubuntu.com/Kernel/Dev/KernelGitGuide).
```
git clone git://kernel.ubuntu.com/ubuntu/ubuntu-xenial.git
# This will take considerable time
```
2. Clone this repository.
```
git clone https://github.com/cilix-lab/ubuntu-wrt.git
```
3. Checkout at a specific Ubuntu release. I've used `Ubuntu-lts-4.10.0-9.11_16.04.2`, so I'd recommend to stick to the same one. Just...
```
cd ubuntu-xenial
git checkout Ubuntu-lts-4.10.0-9.11_16.04.2 -b your-custom-branch

# your-custom-branch can be whatever name you want.
# It'll be the local branch you'll work on.
```
4. Go to this repository's folder and use the merge tool to add the files needed for building the kernel.
```
cd ../ubuntu-wrt
./merge -s ubuntu-xenial -t ../ubuntu-xenial -i
# You can see this script's usage by running ./merge -h
```
This will have copied everything you need to compile the kernel, so...
5. Set the environment variables for building and compile the kernel.
```
export ARCH=arm
export CROSS_COMPILE=arm-none-eabi-
make modules
make zImage
make dtbs
```
**NOTE:** Before running "make dtbs", make sure you have your routers DTS in the "arch/arm/boot/dts" folder. This repository only provides the one for the WRT3200ACM. If it's not there, you probably can get it from somewhere else, I'd start with the McDebian repository.
6. Merge the device tree with the zImage and convert it to u-boot format.
```
# Copy the zImage and append DTB
cp arch/arm/boot/zImage zImage
cat arch/arm/boot/dts/armada-385-linksys-rango.dtb >> zImage

# Convert to U-Boot
mkimage -A arm -O linux -T kernel -C none -a 0x200000 -e 0x200000 -n "linux" -d zImage uImage
```
***NOTE:*** Notice that in my notes I've used WRT3200ACM "armada-385-linksys-rango.dtb" file. Replace that for the proper device tree for your device.
So, the uImage is the file you will flash to the router. All that is left is to prepare the rootfs.
7. If you are familiar with CHROOT environments, this won't be too hard. Just get an ubuntu-minimal installation and add some software. I do the following:
```
export CHROOT=/srv/chroot/ubuntu-wrt

debootstrap --foreign --no-check-gpg --arch=armhf xenial $CHROOT http://ports.ubuntu.com/

cp /usr/bin/qemu-arm-static $CHROOT/usr/bin/

echo "proc $CHROOT/proc proc defaults 0 0" >> /etc/fstab
echo "sysfs $CHROOT/sys sysfs defaults 0 0" >> /etc/fstab
echo "tmpfs $CHROOT/tmp tmpfs defaults 0 0" >> /etc/fstab

chroot $CHROOT
```
***NOTE:*** All these commands will need `sudo` or just do `sudo su`.
Now in the chroot environment:
```
/debootstrap/debootstrap --second-stage
passwd # set your root password
exit
```
Now mount what you've added to fstab by running `mount -a` and go back to the CHROOT `chroot $CHROOT`.
```
# to avoid the locale warnings
dpkg-reconfigure locales

# set hostname
echo UbuntuWRT > /etc/hostname

# add apt sources
echo "deb http://ports.ubuntu.com/ubuntu-ports xenial multiverse" >> /etc/apt/sources.list
echo "deb http://ports.ubuntu.com/ubuntu-ports xenial restricted" >> /etc/apt/sources.list
echo "deb http://ports.ubuntu.com/ubuntu-ports xenial universe" >> /etc/apt/sources.list

# now install all the packages
apt-get update
apt-get install binutils openssh-server ntp ntpdate initramfs-tools bridge-utils isc-dhcp-client isc-dhcp-server bind9 iptables vim iw u-boot-tools mtd-utils pppoeconf vlan pciutils usbutils dbus hostapd wpasupplicant
```
Almost there. Thing is you need to upgrade hostapd and wpa_supplicant to a newer version and, since the kernel is compiled with sch_cake support, if your interested in using SQM, you probably want to go for iproute2 with cake support.
You can build alll this within the CHROOT environment. It will take considerably longer, but you won't have to deal with all the headaches of cross compiling for ARM.
```
cd /usr/src

# install build dependencies
apt-get install build-essential bison flex pkg-config libnl-3-dev libssl-dev libnl-genl-3-dev libnl* libdbus-1-dev libpcsclite-dev libreadline-dev libncurses5 libncurses5-dev git

# iproute2-cake
git clone git://kau.toke.dk/cake/iproute2
cd iproute2
make clean
make
make install
cd ..

# hostapd
git clone git://w1.fi/hostap.git
cd hostap
git checkout hostap_2_6
cd hostapd
cat <<'EOF' > .config
CONFIG_DRIVER_HOSTAP=y
CONFIG_DRIVER_WIRED=y
CONFIG_DRIVER_NL80211=y
CONFIG_LIBNL32=y
CONFIG_DRIVER_NONE=y
CONFIG_IAPP=y
CONFIG_RSN_PREAUTH=y
CONFIG_PEERKEY=y
CONFIG_IEEE80211W=y
CONFIG_EAP=y
CONFIG_ERP=y
CONFIG_EAP_MD5=y
CONFIG_EAP_TLS=y
CONFIG_EAP_MSCHAPV2=y
CONFIG_EAP_PEAP=y
CONFIG_EAP_GTC=y
CONFIG_EAP_TTLS=y
CONFIG_EAP_SIM=y
CONFIG_EAP_AKA=y
CONFIG_EAP_AKA_PRIME=y
CONFIG_EAP_PAX=y
CONFIG_EAP_PSK=y
CONFIG_EAP_PWD=y
CONFIG_EAP_SAKE=y
CONFIG_EAP_GPSK=y
CONFIG_EAP_GPSK_SHA256=y
CONFIG_EAP_FAST=y
CONFIG_WPS=y
CONFIG_WPS_UPNP=y
CONFIG_WPS_NFC=y
CONFIG_EAP_IKEV2=y
CONFIG_EAP_TNC=y
CONFIG_EAP_EKE=y
CONFIG_PKCS12=y
CONFIG_RADIUS_SERVER=y
CONFIG_IPV6=y
CONFIG_IEEE80211R=y
CONFIG_IEEE80211N=y
CONFIG_WNM=y
CONFIG_IEEE80211AC=y
CONFIG_DEBUG_FILE=y
CONFIG_DEBUG_LINUX_TRACING=y
CONFIG_FULL_DYNAMIC_VLAN=y
CONFIG_VLAN_NETLINK=y
CONFIG_TLS=openssl
CONFIG_TLSV11=y
CONFIG_TLSV12=y
CONFIG_INTERWORKING=y
CONFIG_TESTING_OPTIONS=y
CONFIG_ACS=y
EOF
make clean
make
make install

cd ../wpa_supplicant
cat <<'EOF' > .config
CONFIG_DRIVER_WEXT=y
CONFIG_DRIVER_NL80211=y
CONFIG_LIBNL32=y
CONFIG_DRIVER_WIRED=y
CONFIG_DRIVER_NONE=y
CONFIG_IEEE8021X_EAPOL=y
CONFIG_EAP_MD5=y
CONFIG_EAP_MSCHAPV2=y
CONFIG_EAP_TLS=y
CONFIG_EAP_PEAP=y
CONFIG_EAP_TTLS=y
CONFIG_EAP_FAST=y
CONFIG_EAP_GTC=y
CONFIG_EAP_OTP=y
CONFIG_EAP_SIM=y
CONFIG_EAP_PSK=y
CONFIG_EAP_PWD=y
CONFIG_EAP_PAX=y
CONFIG_EAP_LEAP=y
CONFIG_EAP_AKA=y
CONFIG_EAP_AKA_PRIME=y
CONFIG_EAP_SAKE=y
CONFIG_EAP_GPSK=y
CONFIG_EAP_GPSK_SHA256=y
CONFIG_EAP_TNC=y
CONFIG_WPS=y
CONFIG_WPS_ER=y
CONFIG_WPS_REG_DISABLE_OPEN=y
CONFIG_WPS_NFC=y
CONFIG_EAP_IKEV2=y
CONFIG_EAP_EKE=y
CONFIG_PKCS12=y
CONFIG_SMARTCARD=y
CONFIG_PCSC=y
CONFIG_HT_OVERRIDES=y
CONFIG_VHT_OVERRIDES=y
CONFIG_CTRL_IFACE=y
CONFIG_READLINE=y
CONFIG_BACKEND=file
CONFIG_MAIN=main
CONFIG_OS=unix
CONFIG_ELOOP=eloop
CONFIG_L2_PACKET=linux
CONFIG_PEERKEY=y
CONFIG_IEEE80211W=y
CONFIG_TLS=openssl
CONFIG_TLSV11=y
CONFIG_TLSV12=y
CONFIG_CTRL_IFACE_DBUS=y
CONFIG_CTRL_IFACE_DBUS_NEW=y
CONFIG_CTRL_IFACE_DBUS_INTRO=y
CONFIG_IEEE80211R=y
CONFIG_DEBUG_FILE=y
CONFIG_DEBUG_SYSLOG=y
CONFIG_DEBUG_SYSLOG_FACILITY=LOG_DAEMON
CONFIG_DEBUG_LINUX_TRACING=y
CONFIG_DELAYED_MIC_ERROR_REPORT=y
CONFIG_IEEE80211N=y
CONFIG_IEEE80211AC=y
CONFIG_WNM=y
CONFIG_AP=y
CONFIG_P2P=y
CONFIG_TDLS=y
CONFIG_WIFI_DISPLAY=y
CONFIG_AUTOSCAN_EXPONENTIAL=y
CONFIG_AUTOSCAN_PERIODIC=y
EOF
make clean
make
make install

# if you want you can also get SQM scripts (totally optional)
git clone https://github.com/tohojo/sqm-scripts.git
cd sqm-scripts
make install PLATFORM=linux DESTDIR=./current_sqm_base
tar -C ./current_sqm_base -cvf - . | tar -C / -xf -
# fix diffserv
sed -i 's/diffserv3/diffserv4/g' /usr/lib/sqm/defaults.sh

# cleanup build dependencies
apt-get purge build-essential bison flex pkg-config libnl-3-dev libssl-dev libnl-genl-3-dev $(apt-cache search ^libnl | awk '{print $1}' | grep dev) libdbus-1-dev libpcsclite-dev libreadline-dev libncurses5-dev git

exit
```
***NOTE:*** hostapd and wpa_supplicant share files when compiling. So make sure you make clean before compiling each.

That's it. You now have a working rootfs that you can copy to a USB flash drive. You can now use the merge tool to copy the necessary config files from this repository's rootfs folder. For instance, mounting the USB flash drive's partition, formatted as ext4 on `/mnt`:
```
# copy the chroot
tar -cf - -C $CHROOT . | tar -xvf - -C /mnt

# go back to this repository's folder and:
./merge -s rootfs -t /mnt

# finally install the kernel modules to the brand new rootfs
# go to the ubuntu kernel folder
cd ubuntu-xenial
make ARCH=arm CROSS_COMPILE=arm-none-eabi- INSTALL_MOD_PATH=/mnt modules_install
```
***NOTE:*** I frequently use the "LOCALVERSION" variable to set a custom version for the kernel, since I update it frequently because of all the mwlwifi updates. Just add when setting environment variables for the build and when installing the modules.

That's it. You can now flash your router, plug the USB key and it should work. Double check the config files to make sure they will work with your routers interfaces and have a serial adapter to debug in case the network fails to start.

To keep drivers updated, you can keep your rootfs as is and just rebuild the kernel and reflash and reinstall the modules. That's where having custom LOCALVERSION helps.

Hope this helps. Good luck!

**Comment by BoxcarFields** [comment]
@cilix-lab You are awesome. Thank you so much for such detailed notes! I will let you know how it goes. I plan on using 17.04.

**Comment by cilix-lab** [comment]
Good luck, then! Have in mind that if you're using another release, you should manually check every Makefile and Kconfig involved instead of just replacing with the ones on this repository, since they might differ. 
And run "make menuconfig" before compiling the kernel to fix any difference in the configuration file.
You can also check the notes I made on the SNB forums McDebian thread (https://www.snbforums.com/threads/linksys-wrt1900ac-wrt1900acs-wrt1200ac-and-wrt3200acm-router-debian-implementation.28394/page-2).

**Comment by BoxcarFields** [comment]
Got it. Thanks much!
