### ISSUE TITLE
What/How to UbuntuWRT

### ISSUE THREAD

**Issue by Cyb3rT3cky** [cilix-lab/ubuntu-wrt#8]
Hello,

I posted a similar set of questions on SNBForum website but I thought I'd get more response via GitHub so here it goes!  I recently learned about UbuntuWRT being installed on certain routers and it intrigued me to the point that I ended up buying a supported router (Linksys WRT3200ACM) with the goal of running common wireless router functions while utilizing Ubuntu capabilities and qualities at the same time - at least that is the thought!  That being said, I'm a tad confused as to the level of progression you've made on running UbtunuWRT.  The last couple of posts appears to have been about a year ago so I'm hoping I haven't missed out on the opportunity to make the transition.

A little about me, I've flashed a few routers in my time, from DD-WRT, Tomato(s), and OpenWRT, so I have somewhat level of experience, but what I lack is knowing which step-by-step process I would need to take in order to properly transition my currently DD-WRT flashed WRT34200ACM to an Ubuntu/UbuntuWRT?  If anyone would be so kind to help out with a few steps and advice that would be great.  I did see the github page that has links to download Ubuntu 18.04 .bin and ROOTFS but not sure which goes first.  Common sense would suggest formatting a USB flash drive with ext4 partition for the ROOTFS and then somehow load the .bin file..See my dilemma here?  LOL

Any help will be MUCH appreciated!

~ Chad

**Comment by ghost** [comment]
I'm also very curious about this procedure! I have a Linksys WRT3200ACM running DD-WRT.
I tried OpenWRT but went back to DD-WRT after a while (I could not put all WiFi interfaces to work, it had a very slow WiFi).

Now, I definitely wanna try Ubuntu 18.04 on WRT3200ACM! But, how?

It would be AWESOME to support btrfs instead of ext4! Maybe we can run some LXD containers on it! While saving storage space with the btrfs help.

It's kinda bad to depend on a USB Flash drive to use Ubuntu on WRT3200ACM though...

**Comment by cilix-lab** [comment]
It's been quite a while since I updated this repository. You can refer to the [McDebian](https://github.com/Chadster766/McDebian/wiki), since this project was originally based on Chadster766's work and you might find more info on McDebian than on UbuntuWRT.

I haven't been able to push new updates, but I'm trying to find time to update the kernel and base system and switch to loading the kernel image externally (from the USB thumb) instead of flashing it to the router. Don't think that will happen in the next few weeks, though.

Internal flash memory is very limited to run the whole thing and I believe it's safer to use a USB thumb, since if something goes south, you can just switch it for another one.

**Comment by cilix-lab** [comment]
New update out with notes to build yourself.
